---
title: "Peer Review Three"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)

dat<-read_csv(url("https://www.dropbox.com/s/4ebgnkdhhxo5rac/cel_volden_wiseman%20_coursera.csv?raw=1"))

dat$Party<-recode(dat$dem,`1`="Democrat",`0`="Republican")
dat

#######HINT: for Chart D, you'll need to set the height of the renderPlot, using the height argument. Try a value of 750.

#####some data management functions are already included. You need to add the visualization functions.

```


Page 1
======

### Chart A


```{r}
dat %>% 
  drop_na() %>% 
  filter(year>1979) %>% 
  group_by(year,Party) %>% 
  summarise(passed=sum(all_pass)) -> a

ggplot2::ggplot(data = a, mapping = aes(x = year, y = passed, fill = Party)) +
  ggplot2::geom_area() +
  ggplot2::scale_fill_manual(values = c("blue", "red")) +
  ggplot2::labs(x = "Year",
                y = "All Bills Passed",
                title = "Number of Bills Passed Since 1980")

```

Page 2
======

### Chart B

```{r}

dat%>%
  drop_na()%>%
  filter(congress==110) -> b

ggplot2::ggplot(data = b, mapping = aes(x = votepct, y = all_pass, color = Party)) +
  ggplot2::geom_point() +
  ggplot2::geom_smooth() +
  ggplot2::scale_color_manual(values = c("blue", "red")) +
  ggplot2::labs(title = "Passage and Vote Pct., 110th Congress",
                x = "Vote Pct.",
                y = "All Pass") +
  ggplot2::theme(legend.position = "bottom")

```



### Chart C

```{r}
dat%>%
  drop_na()%>%
  filter(congress==110) %>%
  ggplot()
```


Page 3
======

### Chart D

```{r}

####hint: this figure uses selectInput with the multiple option set to true and with the options set up so that all states are initially selected.


dat %>% 
  group_by(st_name) %>% 
  filter(congress==110) %>%
  summarise(passed=sum(all_pass))

```
