---
title: "Peer Review Three"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)
library(DT)

dat<-read_csv(url("https://www.dropbox.com/s/4ebgnkdhhxo5rac/cel_volden_wiseman%20_coursera.csv?raw=1"))

dat$Party<-recode(dat$dem,`1`="Democrat",`0`="Republican")
dat %>% data.frame() -> dat

#######HINT: for Chart D, you'll need to set the height of the renderPlot, using the height argument. Try a value of 750.

#####some data management functions are already included. You need to add the visualization functions.

```


data table
=====================================================================

Column {data-width=1000}
--------------------------------------------------------------------

```{r}

DT::datatable(iris, 
              extensions = "Buttons",
              options = list(pageLength = 100, 
                             scrollY= TRUE,
                             dom = "Blfrtip",
                             buttons = c("copy", "csv", "excel", "pdf")))


```

Page 1
======

### Chart A


```{r}
dat %>% 
  drop_na() %>% 
  filter(year>1979) %>% 
  group_by(year,Party) %>% 
  summarise(passed=sum(all_pass)) -> a

a
```

Page 2
======

### Chart B

```{r}

dat%>%
  drop_na()%>%
  filter(congress==110) %>%
  ggplot
```



### Chart C

```{r}
dat%>%
  drop_na()%>%
  filter(congress==110) %>%
  ggplot()
```


Page 3
======

### Chart D

```{r}

####hint: this figure uses selectInput with the multiple option set to true and with the options set up so that all states are initially selected.


dat %>% 
  group_by(st_name) %>% 
  filter(congress==110) %>%
  summarise(passed=sum(all_pass))

```
